### ISSUE TITLE
Error TypeError: object of type 'NoneType' has no len() in version 1.0.4

### ISSUE THREAD

**Issue by lemcheyWhite** [adamchainz/flake8-tidy-imports#44]
Hi, After the update to version 1.0.4 i received several the same errors:

Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/white/projects/quark/.tox/pep8/local/lib/python2.7/site-packages/flake8/checker.py", line 666, in _run_checks_from_queue
    checker.run_checks(results_queue, statistics_queue)
  File "/home/white/projects/quark/.tox/pep8/local/lib/python2.7/site-packages/flake8/checker.py", line 606, in run_checks
    self.run_ast_checks()
  File "/home/white/projects/quark/.tox/pep8/local/lib/python2.7/site-packages/flake8/checker.py", line 517, in run_ast_checks
    for (line_number, offset, text, check) in runner:
  File "/home/white/projects/quark/.tox/pep8/local/lib/python2.7/site-packages/flake8_tidy_imports.py", line 61, in run
    for err in getattr(self, 'rule_{}'.format(rule))(node):
  File "/home/white/projects/quark/.tox/pep8/local/lib/python2.7/site-packages/flake8_tidy_imports.py", line 113, in rule_I201
    module_names.sort(key=len, reverse=True)
TypeError: object of type 'NoneType' has no len()

Do you have any idea how to fix this?

**Comment by adamchainz** [comment]
Fixed in #43 - upgrade to 1.0.5. Sorry relative imports weren't tested 😱

**Comment by lemcheyWhite** [comment]
Hi, Thank you guys for the quick fix.
